name: Create Release

on:
    workflow_dispatch:
    workflow_call:

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Get Package Version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main

            - name: Use Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Build
              run: |
                  npm ci
                  npm run esbuild

            - name: Package
              id: package
              run: npm run package

            - name: Upload Release Assets
              run: gh release create v${{ steps.package-version.outputs.current-version }} -t v${{ steps.package-version.outputs.current-version }} --target main -F CHANGELOG.md ./*.vsix
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
