name: On Main Push

on:
    push:
        branches:
            - "main"

jobs:
    main:
        runs-on: ubuntu-latest

        outputs:
            label-names: ${{ steps.get-labels.outputs.label-names }}

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Get Package Version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main

            - name: Use Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
                  cache: "npm"
            - run: npm ci
            - run: npm run esbuild

            - name: Get Labels For PR
              id: get-labels
              uses: ./.github/workflows/actions/get-labels
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Bump Version
              uses: ./.github/workflows/actions/bump-version
              with:
                  current-version: ${{ steps.package-version.outputs.current-version}}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  label-names: ${{ steps.get-labels.outputs.label-names }}

            - name: Create Version Bump Pull Request
              id: create-pr
              uses: peter-evans/create-pull-request@v6

            - name: Merge Version Bump Pull Request
              uses: juliangruber/merge-pull-request-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ steps.create-pr.outputs.pull-request-number }}
                  method: squash

    create-release:
        needs: main
        if: ${{ contains(fromJson(needs.main.outputs.label-names), 'release') }}
        uses: ./.github/workflows/create-release.yml
