name: Publish

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Use Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - run: npm ci
            - run: npm run esbuild
            - run: npm run package

            - name: Publish To Extension Marketplace
              run: npm run deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
